Feature/docker framework
feelpp/feelpp-book pull request #26
Opened 2017-01-12 05:05 UTC by prudhomm

Documentation for Feel++ with Docker . Basically the chapter on Docker in the book.

2017-01-12 05:08 UTC, prudhomm commented
@gdolle @boileaum I wrote the pages on introducing and installing Docker. Could you review ?
We need to send the link to these pages to the participants of the course friday the latest

2017-01-12 05:24 UTC, prudhomm commented
I just added a Conventions section in the Preface of the book

2017-01-12 06:01 UTC, prudhomm commented
I just added a section `First Steps `, please review

2017-01-13 01:13 UTC, gdolle requested changes
Some part needs to be rearranged.
- Docker installing should be placed in section 2.1.2 installation/docker(recommended).
 (Or we remove it from installation, as you prefer)
- It would be better to use the docker section just to explain how to use docker (pull, edit, run).
    - "Feel++ container" section ok (push + first run)
    - Section to explain how to mount home directory in    interactive docker, show Feel++ files structures in the container (ls). (PS: This can be done afterwards.)

Wait for feedback (we can see that today IRL 👍 ).

2017-01-13 01:13 UTC, gdolle commented on EN/02-docker/what-is-docker-.adoc
> +Introducing Docker and Containers
This is an introduction to docker. 
This part should be moved directly in the README.md file of the section.

2017-01-13 01:13 UTC, gdolle commented on EN/02-docker/installing-docker.adoc
> +== Channels
Not convinced by this section. It should be shorter and just an introduction sentence like, 
"In this introduction we work only with the "stable" version of docker. (Note there's exist an alpha branch we won't)

2017-01-13 01:13 UTC, gdolle commented on EN/02-docker/installing-docker.adoc
> +== Tested with Docker 1.12
Wrong section level. Also I would remove that section. The version should be mention directly in the introduction when we mention the "stable" version of docker. Maybe it would be better to put a little table

| docker | |
|--- | ---|
| branch | _stable_ |
| version | 1.12 |

2017-01-13 01:13 UTC, gdolle commented on EN/02-docker/installing-docker.adoc
> +Installing Docker
Hum, that section should be in `Installation/docker(recommended)`.
Users will misunderstand otherwise.

Also I would sum up Linux/Mac/Windows in a table directly. (shorter the better (for simple things))

2017-01-13 01:13 UTC, gdolle commented on EN/02-docker/installing-docker.adoc
> +== Installing Docker
Redondent with first level section naming

2017-01-13 01:13 UTC, gdolle commented on EN/02-docker/feelpp-docker.adoc
> +7e6b3a318b2e: Pull complete
Shorten that part with `[...]`

2017-01-13 01:13 UTC, gdolle commented on EN/02-docker/feelpp-docker.adoc
> +Feel++ and Docker
rather "Feel++ containers"

2017-01-13 03:41 UTC, prudhomm commented on EN/02-docker/what-is-docker-.adoc
> +Introducing Docker and Containers
yes may be

2017-01-13 03:42 UTC, prudhomm commented on EN/02-docker/installing-docker.adoc
> +Installing Docker
well, IMO, I think the Installation/Docker(recommended) should point to the Docker section and should be redone.

2017-01-13 03:57 UTC, prudhomm commented
@gdolle I forgot to say that I want a chapter which explains a little bit docker and move/dispatch/redo the content of installation/docker(recommended) to the Docker chapter dans keep basic links in this section

2017-01-13 04:58 UTC, prudhomm commented on EN/02-docker/installing-docker.adoc
> +Installing Docker
I renamed the section Installation

2017-01-13 04:59 UTC, prudhomm commented on EN/02-docker/what-is-docker-.adoc
> +Introducing Docker and Containers
I copied a version in  README but keps the one and rename the section `Introduction` . We will decide which is kept finally

2017-01-13 04:59 UTC, prudhomm commented on EN/02-docker/installing-docker.adoc
> +== Installing Docker
fixed

2017-01-13 04:59 UTC, prudhomm commented on EN/02-docker/feelpp-docker.adoc
> +Feel++ and Docker
done

2017-01-13 10:08 UTC, gdolle commented on EN/02-docker/installing-docker.adoc
> +Installing Docker
I've an idea, maybe we should just merge the Installation/Docker(recommended) in this page. And for Installation->Mac/Linux/Windows section we introduce in bold :
**"We recommend you to try Feel++ using Docker (see docker section +link) before going further in Feel++ installation"**.

What do you think ? (That way we don't have kind of phantom section :) )

2017-01-13 15:21 UTC, prudhomm commented on EN/02-docker/installing-docker.adoc
> +Installing Docker
that's what I want to do. Otherwise it is redundant

2017-01-15 07:30 UTC, prudhomm commented
@gdolle @Trophime @boileaum @romainhild could you review the Installation chapter please ?
I am done with it. I had to re-write most of it.

@gdolle I added the issue/feature #30 - would be awesome to have that for tips, cautions ...

2017-01-15 07:54 UTC, prudhomm commented
it is here https://book.feelpp.org/content/v/feature/docker-framework/EN/01-installation/

2017-01-15 20:35 UTC, prudhomm commented
@feelpp/solving-pdes a first draft of chapters Installation and Docker is now ready. You can review any time. I am now working on the docker images. You should be able to play with the docker images tomorrow.

2017-01-16 04:18 UTC, gdolle commented
@prudhomm If the book still fail, change in the book.json
"template" : "ace"  -> "template" : "default" 
the time I solve the bug. (I'll sleep a bit)

2017-01-16 08:41 UTC, Trophime reviewed
In section 2.1.1 I think that working versions of GCC6 should be specified. My experience is that feelpp compiles with gcc 6.xx but the testsuite and some applications (in hifimagnet) fails depending of the version used. gcc 6.2.0 is working fine for me on Debian/testing whereas gcc 6.2.1 is problematic (no test from testsuite pass!!)

* In the recommended libs hdf5 should be added.
* What about adding med-fichier library?
* At the time of the writing Gmsh default is 2.16

In 2.1.3 to improve readability the command line for installing pre-requistes on Ubuntu are two long. It will be better to like in Debian section use ```/``` to split lines.    

In the same section a note on hdf5/med-fichier may be helpfull for Debian. Maybe this note should appear as a footnote in 2.1.1 section for Salome?

In 2.1.5 I have no preview in gitbook-editor?

In 2.2.3 can we also consider to "deliver" a testsuite component to be able? It will be great to have this kind of "reference" testsuite at least for the team...

```-ti``` should be change to ```-it``` to keep the same notations

2017-01-16 08:45 UTC, Trophime commented
In 2.1.5 it will be nice also to have the feelpp/configure script displayed in the book at least in appendix.
It gives all information needed for the "recommended" pre-requisites for the interested reader.

2017-01-17 09:14 UTC, prudhomm commented
@Trophime thx. I took into account your feedback

2017-01-17 10:05 UTC, Trophime commented on en/01-installation/prerequisites.adoc
> +| HDF5  | --  | --  | Be careful on Debian/sid a new version of HDF5 breaks MED support
HDF5 min=1.8.6 max=1.8.16 for MED support

2017-01-17 10:28 UTC, prudhomm commented on en/01-installation/prerequisites.adoc
> +| HDF5  | --  | --  | Be careful on Debian/sid a new version of HDF5 breaks MED support
fixed

2017-01-24 03:25 UTC, gdolle approved these changes

2017-01-24 03:25 UTC, merged